image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - cleanup_build
  - test
  - deploy
build:
  services:
  - docker:dind
  stage: build
  script: 
  - docker build -t matsskoglund/devkitapi:$CI_JOB_ID .
  - docker tag matsskoglund/devkitapi:$CI_JOB_ID matsskoglund/devkitapi:latest
  - docker tag matsskoglund/devkitapi:$CI_JOB_ID registry.gitlab.com/matsskoglund/devkitapi:$CI_JOB_ID
  - docker tag matsskoglund/devkitapi:latest registry.gitlab.com/matsskoglund/devkitapi:latest
  - docker ps
  - docker login -u=$docker_user -p=$docker_pass
  - docker push matsskoglund/devkitapi:$CI_JOB_ID
  - docker push matsskoglund/devkitapi:latest
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/matsskoglund/devkitapi:latest 
  - docker push registry.gitlab.com/matsskoglund/devkitapi:$CI_JOB_ID 
  tags:
  - Docker
deploy:
  stage: deploy
  script: 
  - echo $(git log -1 --pretty=%B)
  environment:
    name: dockerhub
    url: https://hub.docker.com/r/matsskoglund/devkitapi/

