version: 0.2

env:
  parameter-store:
    docker_user: docker_user
    docker_pass: docker_pass
    DefaultConnection: DefaultConnection
            
phases:
  install:
    commands:
      - echo Configuring DB endpoint
      - sed -i "s/server=127.0.0.1;userid=root;password=mypass;database=devkit;/$DefaultConnection/g" appsettings.json
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install newman --global
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t matsskoglund/devkitapi:latest .
  post_build:
    commands:
      - docker run -d -e ASPNETCORE_ENVIRONMENT=Staging -p 5000:5000 matsskoglund/devkitapi:latest 
      - newman run "https://raw.githubusercontent.com/matsskoglund/DevkitApi/master/test/DevkitApi.Test_Nondestructive.postman_collection.json"
      - docker login -u=$docker_user -p=$docker_pass
      - docker push matsskoglund/devkitapi:latest
artifacts:
  files:
    - imagedefinitions.json    
