version: 0.2

env:
  parameter-store:
    docker_user: docker_user
    docker_pass: docker_pass
    DefaultConnection: DefaultConnection
            
phases:
  install:
    commands:
      - echo Starting the service
      - echo Configuring DB endpoint
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install newman --global
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t matsskoglund/devkitapi:latest .
  post_build:
    commands:
      - docker network create devkitapinet
      - docker network ls
      - docker run --net=devkitapinet --name devkitapidb -e MYSQL_ROOT_PASSWORD=mypass -d mariadb
      - docker run -e ASPNETCORE_ENVIRONMENT=Staging -e DBCONNECTION=$DefaultConnection --net=devkitapinet --name devkitapi -d -p 5000:5000 matsskoglund/devkitapi:latest
      - sleep 10
      - newman run "https://raw.githubusercontent.com/matsskoglund/DevkitApi/master/test/DevkitApi.Test_Nondestructive.postman_collection.json" -x
      - docker stop devkitapidb devkitapi
      - docker network rm devkitapinet
      - docker login -u=$docker_user -p=$docker_pass
      - docker push matsskoglund/devkitapi:latest      
artifacts:
  files:
    - imagedefinitions.json