version: 0.2

env:
  parameter-store:
    docker_user: docker_user
    docker_pass: docker_pass
            
phases:
  install:
    commands:
      - echo Starting the service
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Deploy
artifacts:
  files:
    - imagedefinitions.json