version: 0.2

env:
  parameter-store:
    docker_user: docker_user
    docker_pass: docker_pass
    DefaultConnection: DefaultConnection
            
phases:
  install:
    commands:
      - echo Configuring DB endpoint
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
  post_build:
    commands:
      - echo Updating the service
      - aws ecs update-service --cluster devkit-api --service devkit-service --desired-count 2
artifacts:
  files:
    - imagedefinitions.json    
