version: 0.2

env:
  parameter-store:
    docker_user: docker_user
    docker_pass: docker_pass
    DefaultConnection: DefaultConnection
            
phases:
  install:
    commands:
      - echo Configuring DB endpoint
      - sed -i "s/server=127.0.0.1;userid=root;password=mypass;database=devkit;/$DefaultConnection/g" appsettings.json
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build -t matsskoglund/devkitapi:latest .
  post_build:
    commands:
      - docker login -u=$docker_user -p=$docker_pass
      - docker push matsskoglund/devkitapi:latest
artifacts:
  files:
    - imagedefinitions.json    
