// <auto-generated />
using DevkitApi.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace DevkitApi.Migrations
{
    [DbContext(typeof(DevkitContext))]
    partial class DevkitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DevkitApi.Model.Devkit", b =>
                {
                    b.Property<int>("DevkitID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.HasKey("DevkitID");

                    b.ToTable("Devkit");
                });

            modelBuilder.Entity("DevkitApi.Model.DevkitTools", b =>
                {
                    b.Property<int>("DevkitToolsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DevkitID");

                    b.Property<int>("ToolId");

                    b.Property<string>("ToolType");

                    b.HasKey("DevkitToolsID");

                    b.HasIndex("DevkitID");

                    b.HasIndex("ToolId");

                    b.ToTable("DevkitTools");
                });

            modelBuilder.Entity("DevkitApi.Model.Tool", b =>
                {
                    b.Property<int>("ToolID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aquire");

                    b.Property<string>("AquireType");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("URLRef");

                    b.HasKey("ToolID");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("DevkitApi.Model.DevkitTools", b =>
                {
                    b.HasOne("DevkitApi.Model.Devkit", "Devkit")
                        .WithMany("DevkitTools")
                        .HasForeignKey("DevkitID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevkitApi.Model.Tool", "Tool")
                        .WithMany("DevkitTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
